### ISSUE TITLE
Logging request body.

### ISSUE THREAD

**Issue by blocka** [tilap/koa-request-log#2]
I'm sure this question is not specific to your library but is rather due to my lack of knowlege of both koa and/or node. But maybe you could help anyway.

Is it possible to log the request body as well?

**Comment by tilap** [comment]
@blocka : Koa does not managed request body on the go. You need a middleware like bodyparser. 

Most of the time, those middlewares put the body in the context so you can read them with something like `ctx.request.body` for example.

To log them, you can use the [logger options](https://github.com/tilap/koa-request-log#options):

```
const Koa = require('Koa');
const koaRequestLogger = require('koa-request-logger');
// ....

const app = new Koa();

app.use(myBodyparserMiddleware());

app.use(koaRequestLogger({
  format: (ctx, id, isIn = true, timeDiff = null) => (isIn ?
    `Incoming request #${id}: body ${ctx.request.body}` :
    `Sending request results #${id}: method ${ctx.request.method}, url ${ctx.request.url}, status: ${ctx.status}, duration: ${timeDiff}ms`);
}));
```

Make sure to put the middleware after the bodyparser middleware if you want to log the body on incoming request. And remember that depending on your middleware, you'll have to change `ctx.request.body` by something else.

**Comment by blocka** [comment]
Thanks for your answer. I happen to be using ts-router for this project...I just checked the source and they implement their own body parser based on co-body. Of course by the time that middleware is done, it's too late for logging

When I tried adding in something like koa-bodyparser before my logging middleware, the request hangs. I'm assuming that the body can only be "read" once?

**Comment by tilap** [comment]
I don't know how ts-router works. It seems it packs all-at-once and you cannot add additional middlewares.

You should ask on their github how they deal with that :)
